# Site settings
title: Andrew Quan
email: andrewhquan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
timezone: Asia/Tokyo

linkedin_url: linkedin.com/andrewhquan
github_url: github.com/andrewquan

# Build settings
markdown: kramdown
